language: python

sudo: required
dist: trusty

git:
  depth: 1

#addons:
#  apt:
#    packages:
#    - git
#    - build-essential
#    - automake
#    - libtool
#    - python-dev
#    - gettext
#    - swig

matrix:
  include:
    - name: "Python 2.7"
      python: 2.7

      script:
        - echo compiling enigma2 plugins
        - python -m compileall .
        - echo done!

    - name: "Python 3.8"
      python: 3.8

      script:
        - echo compiling enigma2 plugins
        - python -m compileall .
        - echo done!

